### ISSUE TITLE
Update to Bootstrap 4

### ISSUE THREAD

**Issue by vincentcote87** [SibylLab/Program-Wars#214]
### I have an idea that might make the game better...
Change from bootstrap 3 to bootstrap 4.

**Comment by johnanvik** [comment]
@JaceRiehl, after our discussion the other day, it seems like this would be a major breaking change without gaining us anything substantial. Is that correct?

**Comment by JaceRiehl** [comment]
Yes, that is correct. I didn't find anything in the new version that would be useful to us.

**Comment by johnanvik** [comment]
@strinsberg - Did the recent library update resolve this? Or is this obsolete?

**Comment by strinsberg** [comment]
I think bootstrap is something that we pull from a URL in our index.html file. So upgrading it is probably as simple as changing the URL to point to the next version.

As for how much it will mess us up, I am not sure. But I don't really see how it could as we are mostly just using it for css classes. I will look into it though while I am rebuilding the UI for #526 as it is the best time to do it and make any changes to the code needed.

I have to say I don't know all the things that it adds for us, and I am using mostly my own css when building components to keep the cognitive load low. Probably it would be important if we wanted the game to be able to be played on any size device, but that would require a significant UI redesign again as the new 2 player UI setup would not really work on a mobile phone where there is not room for everything. I think that sort of thing should be added once we have a game and pages that work well on normal PC screens, if it is important.

**Comment by strinsberg** [comment]
I believe that for our project we gain nothing by changing to v4. Also, looking into it v4 is supported by fewer browser editions. Our game may not be fully supported by all browsers anyway, but v3 gives us a better chance of availability for more people. I believe v3 is still fully supported and will be for a long time as I am sure many sites use it. So I see no need in changing it at this time.
