### ISSUE TITLE
Increase size of instructions (and limits)

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/Program-Wars#301]
Perhaps instead of having the user build "small" programs (i.e. 25 instructions) but "large" programs (1000 instructions) by changing the scale of the instruction cards (e.g. 25, 50, 75, 100, 200). This might help the user feel like they are creating something more substantial.

**Comment by JaceRiehl** [comment]
A 200 valued card could be a bit overpowered, you could end up wining with one or two repetition cards.

**Comment by johnanvik** [comment]
The idea would be to change the cards:

1-->25, 2 -->50, 3 --> 75, 4-->100, 5 --> 200

Or maybe 5-->150 and 6-->200?

**Comment by groadybones** [comment]
I'm open to this idea, I remember when call of duty went from 10 points per kill to 100 points per kill in multiplayer (I believe COD 5 was the last one that used units of 10 and MW2 was the first to use units of 100), it just me feel better when I got a kill and received a higher score. I'll apply this new scoring fix as I work on issue #482

**Comment by johnanvik** [comment]
This should be easy enough but will require a redo of the card images.

**Comment by johnanvik** [comment]
On hold with PR #556

**Comment by johnanvik** [comment]
Decided this will require doing too much math for the player.
