### ISSUE TITLE
Don't allow playing repetition cards when no power

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/program-wars#404]
**Describe the bug**
I was under a power outage, but could still play repetitions and variable cards (in my case I could played a Rx and V6). I'm not sure if this makes sense - if the power is out, how can you keep programming? Also, my score bar lept (i.e. went from red to yellow) to reflect this new score. 

**To Reproduce**
 1. Have a power outage played on you
 1. Have a repetition card in your hand
 1. Play the repetition card.

**Expected behavior**
 1. Can't play any card other than "Battery" or "Generator"
 2. The score bar should not be updated (show 0 as there is no power?)

**Screenshots**
![image](https://user-images.githubusercontent.com/28762049/43338008-840f5d10-9192-11e8-9da7-5ab3343e24fa.png)

**Additional context**

**Comment by JaceRiehl** [comment]
This was my bad when the cards were pitched it said that the user can't play instructions. I interpreted that to mean just the instruction cards, so I changed it to this. I'll change it back.

**Comment by johnanvik** [comment]
I also managed to win the game doing this, so this is definitely a bug.

![image](https://user-images.githubusercontent.com/28762049/43338215-f69a96ba-9192-11e8-9ee4-9044397467b5.png)

**Comment by johnanvik** [comment]
I didn't think about this case. 👍 for user testing! :)

**Comment by johnanvik** [comment]
It looks like the AI can still play repeats if they have no power.

**Comment by johnanvik** [comment]
@strinsberg, did you mention that this is still an issue?

**Comment by strinsberg** [comment]
I have not observed this specifically, but I am not looking out for it.

**Comment by strinsberg** [comment]
I will make sure that with #526 it cannot happen. Or with whatever cards that @hastar07 replaces power outages with.

**Comment by strinsberg** [comment]
As power outage has been removed with #526 this is no longer an issue. Any additions of power cards added with #536 can be implemented without this behaviour.
