### ISSUE TITLE
Icons beside players names

### ISSUE THREAD

**Issue by JaceRiehl** [SibylLab/program-wars#413]
From the July 31st meeting: We should have icons beside the player names that allows the user to quickly see what kinds of safety or hazard cards each have played or had played against them.

**Comment by groadybones** [comment]
I think it'd be easier to add this to the modal for viewing a players stacks, also it may cause a performance issue as the game progresses cause it'll be constantly looping through every players active effects.

**Comment by groadybones** [comment]
Actually yeah, I'll implement this when I go to deal with #433

**Comment by johnanvik** [comment]
This will likely be addressed in #526.

**Comment by strinsberg** [comment]
yes this is fixed in #526
