### ISSUE TITLE
Cannot read malware tutorial text

### ISSUE THREAD

**Issue by JaceRiehl** [SibylLab/program-wars#444]
Submitter: Erik Anvik
Email: ejanvik@gmail.com
The box that says "Opponents to infect" blocks the text that would otherwise tell us what malware does. This may or may not apply to other attack cards.

**Comment by johnanvik** [comment]
@hastar07 will be changing the Malware cards, so this can be addressed as part of that change.

**Comment by johnanvik** [comment]
I think this issue was resolved by #555
