### ISSUE TITLE
Power outage effects stop after anyone plays a cybersecurity remedy or safety

### ISSUE THREAD

**Issue by groadybones** [SibylLab/program-wars#471]
Steps to recreate:
1. play power outage
2. wait a few turns
or
1. have power outage played against you
2. wait a few turns

Expected behavior:
Player can't play any cards until power outage is removed

Actual behavior:
After a few rounds player can't continue to play cards as they would normally even with the power outage card active.

**Comment by johnanvik** [comment]
The Power Outage is in effect until either a Generator or Battery Backup is played by the player. This sounds like the correct behaviour.

Are you expecting that Power Outage is only "active" for a few turns?

**Comment by groadybones** [comment]
I've had it where I've had a power outage played on me and for the first few turns I could only play special cards like hacks and overclocks. Then all of a sudden without playing a generator or BB, I was once again able to play instructions, repeats, groups, and instructions. I've also had this happen for the computer when I had played PO against it. I think its possible that opponents playing either BB or generator clears the effects of PO for all players.

**Comment by johnanvik** [comment]
That may be the case. I'm filing this as a bug for further investigation.

**Comment by groadybones** [comment]
After further investigation, it appears any cybersecurity card cancels the effect of power outage however, only BB and generator remove it from the cyberattack field so unless the power outage was cancelled by one of the two, another power outage can't be played against that player cause it they appear to have one played.

**Comment by johnanvik** [comment]
@hastar07, keep this in mind with the changes you are making to PO.

**Comment by johnanvik** [comment]
Verified that this is still a problem.

![image](https://user-images.githubusercontent.com/28762049/83056280-5be7e100-a012-11ea-99eb-fc980b6ad008.png)

**Comment by strinsberg** [comment]
With the removal of the current power outage card in #526 this should no longer be an issue going forward. Any new power outage related cards can be implemented to avoid this behaviour.
