### ISSUE TITLE
Incorporate vue/test-utils

### ISSUE THREAD

**Issue by groadybones** [SibylLab/program-wars#478]
The project currently doesn't have a way to effectively test component contracts. I propose starting a new branch, reworking the testing so we can fully test both the javascript bits and all the components using jest and vue/test-utils as it appears to be the most recommended combination for test vue applications. Also, I haven't been a huge fan of coveralls thus far, could we try some other code coverage system?

**Comment by groadybones** [comment]
Also this will require the project to move from webpack 3 to 4.

**Comment by strinsberg** [comment]
Parts of this issue were fixed with #525. Other testing issues will be addressed in #546.
