### ISSUE TITLE
Reduce card img file size to improve performance

### ISSUE THREAD

**Issue by groadybones** [SibylLab/program-wars#479]
**Describe the bug**
Nearly all of the card image files exceed the 244 KiB recommended for uninhibited performance. 

**To Reproduce**
Run npm build using a webpack 4 version of code

**Screenshots**
![image](https://user-images.githubusercontent.com/47044875/59221151-d8747c00-8b83-11e9-99b4-5b02f57d859f.png)

**Comment by johnanvik** [comment]
Looks like we just need to shrink them by 50-75%.
