### ISSUE TITLE
Combine the concept of end game rewards/bonuses and conditionals

### ISSUE THREAD

**Issue by groadybones** [SibylLab/Program-Wars#481]
**Related issues**
#474 #469 #473 #464 #452

**Is your feature request related to a problem? Please describe.**
The principle of conditionals is poorly represented due to its random nature.

**Describe the solution you'd like**
Instead of controlling the flow of game play into particular fields, we combine the concept of conditionals and the current end game bonuses so that during play, the user sees a list of side objectives formatted as conditional if-else statements with a score boost for if the succeeds in satisfying the conditional and a penalty if they're unable to satisfy the conditional.

**Additional context**
This would require an alternative to the current playfield set up.

**Comment by johnanvik** [comment]
Does PR #500 resolved this?

**Comment by johnanvik** [comment]
This idea has already been incorporated into the game. See PR #572
