### ISSUE TITLE
build/main() playfield redesign

### ISSUE THREAD

**Issue by groadybones** [SibylLab/Program-Wars#482]
**Related issues**
#454  

**To be implemented along with** #481

**Is your feature request related to a problem? Please describe.**
The current representation of grouping doesn't really follow the actual principles of refactoring for code reuse.

**Describe the solution you'd like**
To better convey the principle of grouping, the playing fields will be redesigned so that they no longer represent a conditional if else statement, but now consist of a build field and a main() field. Players build and group stacks in the build field and one a stack has been grouped, players can play call cards in the main() playfield to utilize the stacks they've built. Then repeat/variable cards can be played on top of call cards to modify how many times a group is being called.

**Additional context**
I'd like some input as to how this would affect scoring and hacking, particularly if you think the build playfield should earn the player points towards their program total or if a stack only earns the player points after its been called (players only earn points in the main() playfield). For hacking, I'm thinking group cards should still serve the same purpose of protecting a stack but I think the call cards should still be vulnerable since in the event a call got hacked, the player would still have the group in the build playfield that they could utilize. Lastly, I think there needs to be a system to prevent the player from simply building only one valuable group and calling it over and over.

**Comment by groadybones** [comment]
What would you think of making it so that rX cards can only be played in the build field and variable cards can only be played on a call card and they act as a parameter for the function, in this way if a group is called twice, it can have different repeat values and be worth different points. This would convey the concept of variables slightly better in my opinion while differentiating them from an instruction.

**Comment by groadybones** [comment]
Or we have a completely different card for parameters and they're the ones that are restricted to main

**Comment by johnanvik** [comment]
> the build playfield should earn the player points towards their program total or if a stack only earns the player points after it has been called (players only earn points in the main() playfield).

I think they only get points for when the "method" is called as that is the "running" program from the game's POV.

**Comment by johnanvik** [comment]
To reinforce the concept we're trying to teach let's call the "Build" area "Subroutines" or something similar.

**Comment by johnanvik** [comment]
> For hacking, I'm thinking group cards should still serve the same purpose of protecting a stack but I think the call cards should still be vulnerable since in the event a call got hacked, the player would still have the group in the build playfield that they could utilize.

I agree. An opponent can "hack" a call site, but can't hack the actual stack.

**Comment by johnanvik** [comment]
>  I think there needs to be a system to prevent the player from simply building only one valuable group and calling it over and over.

I'm not sure (yet) if we want to restrict this behaviour. If we do this the way I'm thinking, then a player has to have drawn a "call method" card to make this call, and if there are a limited number of these that will regulate this behaviour. Let's keep an eye on this one and see if it really becomes a problem.

**Comment by johnanvik** [comment]
> What would you think of making it so that rX cards can only be played in the build field and variable cards can only be played on a call card and they act as a parameter for the function

At first I thought "yes", but on further thought, let's wait and see if we need to add this restriction.

**Comment by johnanvik** [comment]
PR #502 partially addresses this.
