### ISSUE TITLE
card images get stuck during long games

### ISSUE THREAD

**Issue by groadybones** [SibylLab/program-wars#484]
**Describe the bug**
During particularly long games, after a while a card image will occasionally get "stuck" on the face image e.g. If I had a group 3 card in my hand at the end of my turn, the image may get stuck so that the card in that position always appears as a group 3 (regardless of whether or not the card should currently be flipped or shown and regardless of what card actually exists in its position) until a new game is started.

**To Reproduce**
1. Go to front menu and start a game
2. Take steps to make the game last for as long as possible
3. Wait for bug to rear its ugly head

**Expected behavior**
Regardless of how long a game takes, cards should show the back image when hidden and their proper face image when shown.

**Comment by johnanvik** [comment]
Something to keep an eye on.

**Comment by strinsberg** [comment]
This should also no longer be an issue after the changes made with #526

**Comment by johnanvik** [comment]
@maimoona-bashir - Please see if you can reproduce this.

**Comment by maimoona-bashir** [comment]
Issue had been resolved. card images no longer get stuck during games.
