### ISSUE TITLE
Generator crashed game

### ISSUE THREAD

**Issue by groadybones** [SibylLab/program-wars#488]
**Describe the bug**
Game was playing perfectly normal until I played a generator card which caused it to crash.

**To Reproduce**
1. Start game
2. Play until generator appears
3. Play generator card

**Expected behavior**
I expected the generator to be grant me protection from PO cards and the game to continue as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/47044875/59799301-482fe880-92a1-11e9-862e-55c0b7105fdb.png)

**Additional context**
Have not had a chance to test if this is a reoccurring issue or if it was just a one time problem

**Comment by groadybones** [comment]
On my next play through, playing a generator card did not cause the same issue so I'm going to mark this as low priority and put it on the backburner

**Comment by groadybones** [comment]
Playing another game and went to play a generator. When I clicked "use" the button became hidden, the modal stayed shown, and no generator was played to my used cards pile

**Comment by johnanvik** [comment]
Needs verification to see if this is still an issue.

**Comment by strinsberg** [comment]
This is unlikely a issue any more as there is no more power outage card so no need for a generator card. Also, with changes for #526, whatever code was causing this will be gone.

**Comment by johnanvik** [comment]
Closing as no longer relevant.
