### ISSUE TITLE
Memory leak leading to crash

### ISSUE THREAD

**Issue by groadybones** [SibylLab/program-wars#490]
**Describe the bug**
Playing a game that froze up so I went to inspect the page with vue dev tools. Dev tools failed to open so I open task manager and saw my memory usage climb steadily until the page crashed

**To Reproduce**
Unfortunately I did not pay attention to the circumstances that caused this behavior so more research will be required.

**Screenshots**
![image](https://user-images.githubusercontent.com/47044875/59886915-5c95e300-937e-11e9-855c-56f5de35b628.png)

**Comment by johnanvik** [comment]
Putting on BackBurner until we can get more information.

**Comment by johnanvik** [comment]
@maimoona-bashir - Something to test and verify.

**Comment by maimoona-bashir** [comment]
![memoryLeakage](https://user-images.githubusercontent.com/63979852/84184346-678fca80-aa4a-11ea-9d85-7df5ce7eb80f.png)
works fine.

**Comment by maimoona-bashir** [comment]
![memoryLeakage](https://user-images.githubusercontent.com/63979852/84184450-99a12c80-aa4a-11ea-83fa-35a5c252a347.png)
Works fine.
