### ISSUE TITLE
Sporadic TypeError causing serious issues

### ISSUE THREAD

**Issue by groadybones** [SibylLab/program-wars#499]
**Describe the bug**
Occasionally when attempting to play a bonus/attack card the game experiences a TypeError when it attempts to use the showFace method but the card is undefined. This results in an array of strange behavior which can be noticed in gameplay such as; when a bonus/attack card is clicked and its pertaining modal pops up, the "cancel button will not appear and if the player clicks "use" the effects of that card may or may not be applied however the modal does not disappear. Instead the becomes unusable and the player must discard it and regardless of whether its effects were applied or not, it does not show up in the used bonus cards or active effects field. 
Note: I tried to play a second game to get a screen shot of the unusable "use" button however the game experienced a crash due to running out of memory and the console lit up with errors pertaining to undefined bonus/attack cards.

**To Reproduce**
At this time it is unknown what causes the card to be undefined and so the bug is only replicate-able through trial and error.

**Expected behavior**
Every time a bonus or attack card is clicked, the game should have a defined card that its working with so that when showFace is called, it performs as it should.

**Screenshots**
First playthrough:
![image](https://user-images.githubusercontent.com/47044875/61189539-187bc280-a64c-11e9-93ad-e70598f7f283.png)

Second playthrough: (there were 20 new errors generated after the crash)
![image](https://user-images.githubusercontent.com/47044875/61189689-2599b100-a64e-11e9-99e3-c0bba579286f.png)

**Additional context**
I believe most of the buggy-ness of the bonus/attack cards revolves around this current issue due to fact that in the code I continue to see cases where exceptions have been made to handle undefined cards.

**Comment by johnanvik** [comment]
Until we can reliably reproduce this, I'm putting it on the BackBurner.

**Comment by johnanvik** [comment]
Closing as this bug has never been seen again...
