### ISSUE TITLE
Conditionals grant bonus card effects

### ISSUE THREAD

**Issue by groadybones** [SibylLab/Program-Wars#500]
**Describe the solution you'd like**
Have conditionals that are able to offer the player bonus card effects (e.g. battery backup, firewall)

**Details you've considered**
Tie the three most commonly played base cards to the three bonus cards so that the player has another (and far more realistically achievable) way to achieve the "safe programming" bonus. Because the most devastating attack card is power outage and the card that a player is likely to play the soonest, but also the most likely to be removed from the playfield (via hacking or grouping) is instructions, I think the bonus that it would be tied to should be generator so that players could get protection from protection from power outages early on, but could become exposed to them later if they're not careful to balance their grouping and instructions OR it allows a player to be tactical and set up multi-staged attacks where they hack one turn and play PO the next which adds a little depth to the game. Since the seemingly preferred bonus card (by review) is Firewall and its effect is similar to that of the group card in that is blocks hacking, and since in the late game most of a players stacks are already grouped, it makes sense to have a conditional that would tie group cards to the firewall effect but set up the conditional so that it would be hard for the player to achieve until late game. In that way, the actual Firewall bonus card still retains its bonus status cause it could grant a player protection if they draw it early-mid game. Lastly, repeats would be tied to Antivirus for 2 reasons; the other bonus cards effects are already used and the way each card affects the game play into each other. Because virus' and overclocking (and ergo antivirus because it pertains to these) affect the players score by a percentage, their effects are easier to see as the players score grows. Repeats tie into this because they're an effective method of getting points on the board.

**Comment by johnanvik** [comment]
Closing this, as this request seems to be in reaction to Power Outage cards, which have now been removed from the game.
