### ISSUE TITLE
Overclock played on power outage?

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/program-wars#507]
**Describe the bug**
During play, the AI seemed to be able to play an Overclock with an active PowerOutage. This does not make sense.

**To Reproduce**
1. Be under a PowerOutage
2. Play an Overclock
3. Play is allowed.

**Expected behavior**
Overclock cannot be played in this situation as the "computer is not running".

**Comment by johnanvik** [comment]
On hold until @hastar07 redoes Power Outage

**Comment by strinsberg** [comment]
This should no longer be an issue once #526 has been finished.

We have removed the power outage card. It may be re-introduced as other cards by @hastar07 in #536 or have similar functionality added to a card in #534.
