### ISSUE TITLE
Update Tutorial

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/Program-Wars#510]
With the change in the gameplay / UI as a result of Issue #482, the tutorial will need to be updated to reflect changes.

Revert changes made for #504 when completed.

**Comment by johnanvik** [comment]
@maimoona-bashir - this could be a good project to work on, or we may decide that @strinsberg information overlays are sufficient.

**Comment by johnanvik** [comment]
@strinsberg, @maimoona-bashir, @hastar07 - do you think we need this? I'm thinking that the overlays are enough. 

The original tutorial was a variation of the PW game where the player is given specific cards and then asked to play them in a specific order. With UI and game changes, this quickly became out of date and hard to maintain (and never worked right anyway). I'm inclined to let this "Jack" slip quietly into the deep icy Atlantic ocean (yes, that is a reference to the movie "Titanic").

**Comment by hastar07** [comment]
Yes tutorial specially a video will be more effective in terms of understanding the gameplay.

**Comment by strinsberg** [comment]
I agree the info popups and future rules updates will replace this nicely. If we include some GIFs in the rules it will likely give most of what players need to get started.

I also like the idea of a tutorial videos for each game tier that we make. Players could have links to these and you could explicitly tell people in the user study to watch each video before they start so they know what is going on.
