### ISSUE TITLE
Change cyberattack modal to overlay

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/program-wars#528]
**Describe the solution you'd like**
Could we have it when Hack is clicked, an overlay is provided that shows the players who can be hacked (i.e. don't have a Firewall and have at least one stack that is not grouped). The user can then select the player they want to Hack. 

**Additional context**
The addition of an overlay for discarding got me thinking about having something similar for Hack. We could even remove the selection of which stack to attack by the player by having the highest scoring stack be automatically removed.

**Comment by johnanvik** [comment]
This idea applies to other cyberattacks like Malware and Power Outage

**Comment by strinsberg** [comment]
Would it make sense with this change to make the card selection also look different if the card cannot be played? Say changing the glow from green to red? Or putting an X over the card with a little tooltip or something that says there is nowhere to play the card. Might be especially useful for the hacker card if there are no opponents to hack. Even with base cards this could be useful if there is no stack to play the card on to have more of an indication than just not showing any add buttons.

I will try mocking up some visuals to for different possibilities while I work on the adding the overlays and removing the modals.

**Comment by strinsberg** [comment]
Aside from the lack of style do these examples fit with your idea?

The card types aren't correct for now, these are just to show one way of we could approach it.

![Screenshot from 2020-05-14 16-32-27](https://user-images.githubusercontent.com/45857986/81992984-f94e1880-9601-11ea-9747-075e1ec589e0.png)

![Screenshot from 2020-05-14 16-35-01](https://user-images.githubusercontent.com/45857986/81992997-ffdc9000-9601-11ea-9be5-04590a50d574.png)

![Screenshot from 2020-05-14 16-33-23](https://user-images.githubusercontent.com/45857986/81993005-0408ad80-9602-11ea-8e33-5c6d13d4e4ea.png)

![Screenshot from 2020-05-14 16-36-43](https://user-images.githubusercontent.com/45857986/81993013-0965f800-9602-11ea-893f-4defc6220b2e.png)

**Comment by strinsberg** [comment]
We could also try a modal like overlay that will offer some of the same options, but it a slightly less intrusive UI. Something like the below, but probably with better styling.

![Screenshot from 2020-05-14 15-35-51](https://user-images.githubusercontent.com/45857986/81994812-eb01fb80-9605-11ea-9b8e-621db6d78271.png)

**Comment by johnanvik** [comment]
> Would it make sense with this change to make the card selection also look different if the card cannot be played? Say changing the glow from green to red? Or putting an X over the card with a little tooltip or something that says there is nowhere to play the card. Might be especially useful for the hacker card if there are no opponents to hack. Even with base cards this could be useful if there is no stack to play the card on to have more of an indication than just not showing any add buttons.

@hastar07 will be doing this as part of his thesis.

**Comment by johnanvik** [comment]
> We could also try a modal like overlay that will offer some of the same options, but it a slightly less intrusive UI. Something like the below, but probably with better styling.
> 
> ![Screenshot from 2020-05-14 15-35-51](https://user-images.githubusercontent.com/45857986/81994812-eb01fb80-9605-11ea-9b8e-621db6d78271.png)

I like this one. Seems clear what is happening.

**Comment by strinsberg** [comment]
So I thought I would post an update to show what how the progress on this looks so far.

![attack_none](https://user-images.githubusercontent.com/45857986/82479729-0058a900-9a90-11ea-8cf9-0bd2b0344f38.png)
![attack_targets](https://user-images.githubusercontent.com/45857986/82479730-0189d600-9a90-11ea-82aa-4bad11600ae9.png)
![activate_already_used](https://user-images.githubusercontent.com/45857986/82479733-0189d600-9a90-11ea-860a-c96713c0df17.png)
![activate_safety](https://user-images.githubusercontent.com/45857986/82479734-02226c80-9a90-11ea-98d7-4afe13da2d56.png)

Probably it makes sense to make the overlay for no targets just a message and not a button like the *In Use* message for safety cards. Those kinds of changes are pretty easy to make.
