### ISSUE TITLE
Do not confirm playing safety

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/program-wars#529]
**Is your feature request related to a problem? Please describe.**
When you select a safety (e.g. Firewall), a modal pops up asking if you want to play it, or discard it. Given that a player will always choose to play it, this question seems unnecessary.

**Describe the solution you'd like**
Clicking on a safety automatically plays it. If a player already has that safety on the board, the card is discarded.

**Comment by johnanvik** [comment]
May want to consider doing the same for remedies.

**Comment by maimoona-bashir** [comment]
Sometimes a player clicks the button by mistake, in that case, it is necessary to ask; do you want to play it or discard it.

**Comment by johnanvik** [comment]
Good point. How about we reduce the size of the popup?

**Comment by johnanvik** [comment]
@maimoona-bashir, look at @strinsberg proposal in #528. What if we do something like that?

**Comment by johnanvik** [comment]
Resolved by #528
