### ISSUE TITLE
Game logs

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/Program-Wars#530]
**Is your feature request related to a problem? Please describe.**
When testing, it can sometimes be hard to tell if a bu has occurred. For example, I was playing a game and it seemed like the AI was able to hack one of my stacks when I had a Firewall.

**Describe the solution you'd like**
A textual log that describes what cards were played. This will help with debugging, but can also be useful for the player to see what cards were played.

**Describe alternatives you've considered**
A visual log that shows the images of the cards played.

**Comment by strinsberg** [comment]
In the fixes along with #526 cards played are tracked to be used with side objectives. It is possible that some of the functionality used to make this happen can be extended by @maimoona-bashir when creating game logs.

**Comment by johnanvik** [comment]
This is from the documentation of `loglevel` (https://pimterry.github.io/loglevel/), but it provides a good idea of the different types of messages that a log can have.

![image](https://user-images.githubusercontent.com/28762049/84807526-99fa7400-afc4-11ea-8fa7-bb327706425a.png)

**Comment by maimoona-bashir** [comment]
issue resolved in test(log) #597
