### ISSUE TITLE
Move current score to end of progress bar

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/program-wars#531]
**Is your feature request related to a problem? Please describe.**
A player's current score/progress is found in two different places: The top of the stack panel and the progress bar. These seem disconnected.

**Describe the solution you'd like**
Move the player's total score to the end of the progress bar so this information is grouped together.

**Describe alternatives you've considered**
Have the current score shown along with target score at the top of the screen.

**Comment by maimoona-bashir** [comment]
target score, players score and progress bar on the left.

**Comment by maimoona-bashir** [comment]
![Score_edited](https://user-images.githubusercontent.com/63979852/82183468-4997d580-98a3-11ea-8b33-9c600cb62758.jpg)

**Comment by johnanvik** [comment]
@maimoona-bashir, Did you create a pull request for this?

**Comment by maimoona-bashir** [comment]
this is mockup. i just wanted to make sure, is this what you want?
