### ISSUE TITLE
Specializing the Malware card

### ISSUE THREAD

**Issue by hastar07** [SibylLab/Program-Wars#534]
**Is your feature request related to a problem? Please describe.**
Currently, the Malware card represents a general cybersecurity concept. To further educate players on the specifics, this card will be replaced by four cards representing the different types of Malware. 

**Describe the solution you'd like**
The new cards will be:

**_Trojan (Trojan horse)_** is any malware that misleads users as to its true intent. A player can use this card to mislead opponents about their score.

> **Idea:**  Suppose player ‘A’ actual score is 25. Now, if the opponent player ‘B’ played, the Trojan card, player ‘A’ will see his score in the UI as 15. This action will mislead the player ‘A’ how close the player is to complete the target.
> **Solution:** The Anti-virus card will be able to remove the effect of Trojan. The effect will be permanent if the player does not have any Anti-virus card. The important thing, all the other player, will see the original score of the affected player except the player him/herself. 

**_Ransomware_** is malware that intends to publish the affected individual data unless a specific payment or penalty is paid. It also involves the user’s files being encrypted and a key only provided when the “ransom” is paid. 

> **Idea:** This card can be played to reduce specific points of the opponent and add the same amount to the attacker score. 
> Suppose player ‘A’ score is 25, and player ‘B’ score is 10. Now, if player ‘B’ played, the Ransomware card against player ‘A’. Player ‘A’ score will be reduced to 15, and player ‘B’ score will be increased by 20.
> **Solution:** The Anti-virus card will be able to remove the effect of Ransomware. If the affected player does not have any Anti-virus card, the outcome will be permanent.  

**_Virus_** is typically a computer program that replicates itself by modifying other programs. 

> **Idea:** This card will target an instruction (as “instruction set” has a different meaning in CS) of the opponent, which has a maximum point and make it zero. 
> Suppose player ‘A’ score is 25 and has a stack that contains the maximum point 10. Now, if some other player attack player ‘A’ with the Virus card, that stack containing the maximum point will be zero. So temporarily player ‘A’ current score will be 15.
> **Solution:** The Anti-virus card will be able to remove the effect of Virus. If the affected player does not have any Anti-virus card, the outcome will be permanent.  

**_Spyware_** is a malware used to gather information and send it to another party without the host’s consent. 

> **Idea:** This card can be played to get information about opponent cards(random three cards in hand). 
> Suppose some other player is attacked player ‘A’. Now, the attacker will be able to see three random cards that player ‘A’ holds. 
> **Solution:** Again, the effect of this card can be prevented by the Anti-virus card.

**Describe alternatives you've considered**

**Additional context**
![Specializing the Malware card](https://user-images.githubusercontent.com/57976176/81728624-fe676800-9447-11ea-9bba-36fbacd043d4.png)

**Comment by strinsberg** [comment]
I have coded in the new VIRUS card that has been discussed as a prototype. It can be added to a stack. It both makes the stack worth 0 points and prevents playing on the stack. Stacks that are under viruses also cannot be grouped.

It can be dragged to an opponents stack just like the hack card, and will add to the top of the stack. Below are some screenshots.
![Screenshot from 2020-06-16 16-32-36](https://user-images.githubusercontent.com/45857986/84834916-ba8bf380-afef-11ea-85f8-c28c68a38aca.png)
![Screenshot from 2020-06-16 16-33-09](https://user-images.githubusercontent.com/45857986/84834926-c081d480-afef-11ea-957b-5ecc527203c6.png)
![Screenshot from 2020-06-16 16-34-03](https://user-images.githubusercontent.com/45857986/84834935-c677b580-afef-11ea-8b3a-1b4b6656bb55.png)

It cannot be removed yet so I have not pushed any commits to a branch for now. Just to show what we can do with it.

**Comment by hastar07** [comment]
There are some new remedy cards like scan, firewall and anti-virus.
Now all are in the testing mode for some bug fixing.
