### ISSUE TITLE
Introducing Algorithm Cards

### ISSUE THREAD

**Issue by hastar07** [SibylLab/Program-Wars#535]
**Is your feature request related to a problem? Please describe.**
For making the game more competitive, two different types of algorithms will be introduced into the game, specifically sorting and searching. 

**Describe the solution you'd like**
### Implementation of Sorting Algorithm
 Sorting is arranging items into an ordered sequence. A new card will be introduced that allows the player to arrange the top 5 cards of the deck. Here the player will have the freedom to choose the order. A player will earn additional points by playing a sorting card, which will motivate the player to use this card.
 
### Implementation of Searching Algorithm
 Searching is the process of locating a particular element present in a given set of elements. By playing a searching card, a player can choose a specific card among the top 5 cards from the deck. Again, to encourage a player to play this card, bonus points will be awarded.

**Describe alternatives you've considered**

**Additional context**
![algorithm cards](https://user-images.githubusercontent.com/57976176/81729287-fe1b9c80-9448-11ea-8b3f-0b0ae84fc1c5.png)

**Comment by strinsberg** [comment]
I think both of these are pretty solid and standard card game card ideas that fit well with the programming concepts.

I think they would both be valuable and important if we wanted to eliminate the redraw button. If you cannot redraw your hand you are much more likely to want to see and organise the next 5 cards of the deck or search for a card.

I think the sort card is more valuable in games where there are fewer players or each player has their own deck. This way the card order is much more valuable to you. In a 4 player game sorting the top 5 cards means that you will see 1 of them and the other 4 will go to your opponents. This may be good if there is one card among them that you really need, but does not add as much strategy as being able to help plan more than one of your upcoming turns.

**Comment by hastar07** [comment]
For search card: 
It might be specific card a player want, say I have Rx card in my hand so I want a variable card. Now if I have a search card into my hand, I can apply a search option with a specific message Like "Search-Variable card". 
For more interesting :
Say my "Search card" is using "linear search method" so I will get "Variable card" after 4 turns .
And if my "Search card" is using "Binary search method" I can get "Variable card" after 2 turns .
So the player can get an idea of complexity.

**Comment by hastar07** [comment]
For sorting:
Player can apply "ascending or descending" order of sorting.
If player choose descending order: Deck will be sorted with highest value, say in a random way Instruction card came in a random order, but after sorting highest "Insruction card" will come first. Player can apply sort algorithm to a specific card type. So sort can only apply to a single card type: Instruction or Repeation or Variable or Group

**Comment by strinsberg** [comment]
I know we want to have these in v2 as well, but they are now available in version 3. The code is so different, I felt I needed to add them because I would not be able to integrate any version 2 code that implements them.
