### ISSUE TITLE
User Interface modifications

### ISSUE THREAD

**Issue by hastar07** [SibylLab/Program-Wars#537]
**Gameplay Problem**
### Indicating playable cards
  The user interface provides a view of the player’s hand. Among those cards, all might not be eligible for playing. This feature will provide feedback for the players as to what cards can be currently played by toggling or glowing. For example, linking with R_x -->V cards (disable V cards, unless R_x played). 
 
### Separating functions from the `main program'
  Currently, there is only one playing area for cards. One of the gameplay modifications will facilitate the introduction of a new card for representing when a method/function is called in a program. To support the action, the current play area will be separated into two areas. For example, the main part of the program can be stored in the main stack, and if there are some methods like printf(), scanf() can be created in a functional area, which will be denoted as an auxiliary stack.

**Screenshots**

**Comment by johnanvik** [comment]
The first item was done as part of the redesign in PR #574.

The second item will be done as part of #538.
