### ISSUE TITLE
Method card (M)

### ISSUE THREAD

**Issue by hastar07** [SibylLab/Program-Wars#538]
**Is your feature request related to a problem? Please describe.**
This card will represent a function or method created by the player in the "Function/Method" area of the UI.

**Describe the solution you'd like**
Add a new card

**Describe alternatives you've considered**

**Additional context**
![Method Card](https://user-images.githubusercontent.com/57976176/81731621-6d46c000-944c-11ea-8a4e-df43deca2a06.jpg)

**Comment by johnanvik** [comment]
@strinsberg will implement this in consultation with @hastar07 and @johnanvik.

**Comment by johnanvik** [comment]
#482 is also addressed by this.
