### ISSUE TITLE
Re-integrate or find new services for Coverage and Code quality

### ISSUE THREAD

**Issue by strinsberg** [SibylLab/Program-Wars#544]
After the dependency update our project is no longer integrated with Coveralls. We need to either figure out how to get this working again, switch to another service, or change how we track coverage. Unit testing is now done with Jest and it is setup to generate coverage reports both at the command line and in an html. We may be able to setup the badge on the home page to track this coverage report when CI runs. It may also be possible to save the html coverage to preview for each recent CI run. It may also not be that difficult to setup the jest coverage to work with coveralls again.

We also have a deepscan badge in the readme that I am not sure how it interfaces with the repo. It may do this through a WebHook that I can't see with my project permissions. In this case it may not require any updating. Unless it uses some configuration that has changed with the project update.

We also have a .codeclimates.yml-breaks file in the repo. I am not sure what this integrates with. If it was a package that was removed it may no longer work properly. It may be related to the Travis build in some way that I don't know. But if it was doing something we want we will need to confirm it is still happening or change what we are doing.

**Comment by johnanvik** [comment]
This seems to have been addressed by #607, correct?

**Comment by strinsberg** [comment]
The code coverage part of it was, but I never did get the deepscan working. Even with your approval I could not see the organization on my deepscan account. So the badge still points to the old repo. Might be something that you could fix on deepscan and then we could just do a small merge request for changing the badge.

**Comment by johnanvik** [comment]
I'll look into the DeepScan issue.
