### ISSUE TITLE
Cannot replace variables

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/program-wars#558]
**Describe the bug**
You cannot replace a variable card with another variable card. 

**To Reproduce**
1. Play a variable card on a `Rx` card
2. Get another variable card in hand
3. Click on variable card in hand
4. There is no option to replace the variable card in play.

**Expected behavior**
Variable cards can be changed. This was the original intent - you could change the value of variable.

**Screenshots**
![image](https://user-images.githubusercontent.com/28762049/83042606-1372f800-9fff-11ea-814b-a9f91c5ad7e1.png)

**Comment by strinsberg** [comment]
Sorry If I am sniping all the issues, but this has been/will be fixed in #526. It was easy to do along with adding the ability to add cards to stacks with drag and drop.

**Comment by strinsberg** [comment]
In #526 we have addressed this.

If a variable card is played on a stack with variables in it the stack will have the smallest variable card replaced by the new card. We can wait to see how play testing goes to decide if this is the best fix or if we want to try any different solutions.

**Comment by maimoona-bashir** [comment]
![variable](https://user-images.githubusercontent.com/63979852/84185729-a9217500-aa4c-11ea-84ea-60310177cf00.png)
Works fine!
