### ISSUE TITLE
Make the new card effect icons more visual distinct

### ISSUE THREAD

**Issue by strinsberg** [SibylLab/Program-Wars#561]
**Is your feature request related to a problem? Please describe.**
The mini card icons are not super easy to tell apart.

**Describe the solution you'd like**
Adjust the colours a little bit on images that look similar. Either the background colour or the colour in the card image. Try and enlarge the card image as much as possible so it is distinct. Remove any text that might obscure the image or would allow it to be made bigger if the text were gone.

**Describe alternatives you've considered**
I will be adding tooltips to these images along with the other work in #526, but they were created in haste to have something that works. I think they do the trick for someone who stares at them all day, but could be made better for the general user.

I also think that it is important that they look as close to the cards as possible so that it requires less thinking for a user to see what effects are applied to them. Ideally, after a few games they will not need to mouse over to see what effect is applied because the image will be enough.

**Additional context**
Here is a screenshot
![image](https://user-images.githubusercontent.com/45857986/83312687-7b2c6d00-a1d0-11ea-8367-a942915f5882.png)

Whoever works on this can ask me for the image files if they get started before #526 is close to ready.

**Comment by strinsberg** [comment]
I have improved the icons so that they don't have text and the logo is all that they contain.
![FIREWALL](https://user-images.githubusercontent.com/45857986/85315413-42528180-b478-11ea-9f16-a36d1dcc8f82.png)
![SCAN](https://user-images.githubusercontent.com/45857986/85315415-42eb1800-b478-11ea-91d1-6ad73a1ade32.png)
![RANSOM](https://user-images.githubusercontent.com/45857986/85315416-4383ae80-b478-11ea-914a-564845360e39.png)
![SPYWARE](https://user-images.githubusercontent.com/45857986/85315419-4383ae80-b478-11ea-8ada-0c5c39401ff4.png)
![ANTIVIRUS](https://user-images.githubusercontent.com/45857986/85315420-441c4500-b478-11ea-8e53-0cb9f7a0392a.png)

I think they will be more user friendly now, but will wait for play testing to confirm this.

**Comment by johnanvik** [comment]
Yes, these look better without the text. Perhaps, we add a tool-tip/hover text for if the player needs a reminder now that the text is gone.

**Comment by strinsberg** [comment]
There is currently a tooltip that says what the effect does that can be seen on mouseover (or at least should be)

**Comment by strinsberg** [comment]
I am going to close this as it has been addressed. The next set of updates should provide an improved experience and we can add new issues for future concerns.
