### ISSUE TITLE
Square and round card edges

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/Program-Wars#569]
**Describe the bug**
Cards have square edges, Card backs have round edges.

**Expected behavior**
Card images should have consistent edges.

**Screenshots**
Card fronts
![image](https://user-images.githubusercontent.com/28762049/83926827-3bbdcd80-a748-11ea-9e16-0850a979392b.png)

Card backs
![image](https://user-images.githubusercontent.com/28762049/83926867-56904200-a748-11ea-9d71-b92c55a46303.png)

**Comment by jsanvik** [comment]
It's simpler to add square edges to the single back card file than to add rounded ones to every front card file.
Are we dead set on round edges, or can I just change the back file to square corners?
If so, does anyone know how I can access that back file?

**Comment by strinsberg** [comment]
I support the idea of just making the back of the card have square edges instead of converting all other cards to round edges.

images for cards are in `public/static/cardImg` on the master branch

**Comment by strinsberg** [comment]
I added one of new images by @jsanvik to the game (hopefully not prematurely). This is what it looks like in game.
![Screenshot from 2020-06-15 17-26-36](https://user-images.githubusercontent.com/45857986/84716417-476f7800-af30-11ea-9b96-fe2f232d7569.png)

**Comment by strinsberg** [comment]
I have added these new card backs to the game and they look good. So the issue is resolved.
