### ISSUE TITLE
Add proper user help back to the game

### ISSUE THREAD

**Issue by strinsberg** [SibylLab/Program-Wars#586]
**Is your feature request related to a problem? Please describe.**
The rules modal is now out of date for the v2.5 game.

**Describe the solution you'd like**
We need to re-write the rules so that they describe the components and actions a player can take well. We can include some GIFs and screenshots of different actions to make the drag and drop usage clear.

The current modal for the rules can be a bit awkward. I would like to split it up into a set of pages that can be opened in a new tab. That way it does not interrupt the game in the same way, and the player can have the rules open and switch back and forth if they need to.

**Comment by strinsberg** [comment]
@hastar07 is going to work on getting minimal rules working for the current 'base' game. We will chop the component into smaller components and make the rules more detailed as things become more solid.

**Comment by strinsberg** [comment]
I believe that @hastar07 has completed a google doc for updating the rules. I am going to at some point for version 3 (and probably we can add it to v2 as well) putting the rules into an actual separate html page that can open in a new tab. This way a person can open the rules without it affecting the game. They could also just leave the tab open while they play and switch to it to look up rules when they need.

The other benefit of this (the main reason for doing it) is that it will make it much easier to present a clean and clear description of the rules, as well as split the code for each section of rules up into multiple components that can be easier to work on to make the content better.

**Comment by johnanvik** [comment]
@hastar07, please attach a PDF version of the draft of rules here for review (and progress tracking).

**Comment by strinsberg** [comment]
I am going to try to setup a minimal structure for the new help pages for version 2.5. I am going to test out a markdown component for vue that may allow us to write and style most of the text for each page with markdown instead of HTML. This will make updating rules much easier overall and will require less coding to do so. I don't think the markdown component will do images so we may still have to add those with HTML, but I don't think that is a big deal.
