### ISSUE TITLE
"Report Issue" not working

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/Program-Wars#593]
**Describe the bug**
I tried reporting an issue using the "Report Issue" menu item. Didn't look like it made it to the project. 

**To Reproduce**
1. Go to "Report Issue" in the menu
2. Report an issue.
1. Nothing appears in the GitHub project.

**Expected behavior**
An issue to appear in the issue tracker on GitHub.

**Additional context**
Likely due to the project moving to `Sibyl Lab`

**Comment by johnanvik** [comment]
@maimoona-bashir, please provide an update on what you found with this. I think we got it working again, right?

**Comment by maimoona-bashir** [comment]
yes, it is working now.
