### ISSUE TITLE
The bonuses do not properly reflect the new cards being added for malware

### ISSUE THREAD

**Issue by strinsberg** [SibylLab/Program-Wars#596]
**Gameplay Problem**
The bonuses are not correct anymore for added cards. They need to be updated and tested again.

**Screenshots**
Here I have only the antivirus and got Defensive bonus which is supposed to be fore having both antivirus and firewall (most likely due to the way protection works now)
![Screenshot from 2020-06-20 20-15-14](https://user-images.githubusercontent.com/45857986/85312038-8727e980-b473-11ea-8660-e549bb0ada60.png)

Here both players are getting the clean bonus but they have malware
![Screenshot from 2020-06-22 10-35-32](https://user-images.githubusercontent.com/45857986/85312585-3ebcfb80-b474-11ea-8d95-0b65354fe3e7.png)

**Comment by strinsberg** [comment]
This will actually require most of the changes to the functions that compute bonuses in the `src/classes/game/Objectives.js` file. Some small changes to names of bonuses may be needed in the `src/components/modals/WinnersModal.vue` for the visual side of things.

**Complete Program** needs to become **Nested Loops** and it should award 2 points for each stack that the player has where `stack.isComplete()` returns `true`. The scoring change can be made by adding something like the following to `Objectives.js` where complete bonus is calculated `stacks.filter(s => s.playerId === player.id && s.isComplete()` the number of stacks that are returned can be multiplied by 2 and added to the score.

**Defensive Programmer** needs to be updated just return true if the player has 'ANTIVIRUS' as it is no longer possible to have all safeties on you at once. Antivirus is the one that covers everything. Might even what to remove this bonus since we give bonuses for playing safeties as well.

**Clean System** needs to be updated in the `Objectives.js` class to check for all types of malware now that VIRUS is not an effect. This will require looking at all of a players stacks to ensure none have 'VIRUS' cards on top. It will also require inspecting a players hand to ensure that they do not have any cards that `isMimic` is true for.

**Comment by maimoona-bashir** [comment]
![cleanSystem](https://user-images.githubusercontent.com/63979852/85799836-27447380-b6fd-11ea-8471-06eff04702bc.PNG)

**Comment by strinsberg** [comment]
we have fixed this up
- Defensive bonus gives 10 for Antivirus, 5 for Firewall, 0 for scan
- Safety bonus give 3 per safety played, also includes Scan. This is because the safety bonuses stacked quite a bit. Playing antivirus gave 10 for safety, 10 for clean, and 10 for defensive. That seems like too much.
- Clean bonus now properly only gives the bonus if you have no Ransom, Spyware, Trojan, or virus active on you when game ends.
- Nested Loops give 5 points per completed stack (2 repeats and Rx has variable)

![Screenshot from 2020-06-26 15-28-06](https://user-images.githubusercontent.com/45857986/85902864-3ccfa100-b7c2-11ea-9016-1dd8c08a3f4e.png)
