### ISSUE TITLE
Playing "Scan" shows as Overclock in the log

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/Program-Wars#600]
**Describe the bug**
When a "Scan" card is played, the logs show the card as "Overclock".

**To Reproduce**
1. Play a "Scan" card.
2. Examine logs.

**Expected behavior**
The logs show a "Scan" card was played.

**Additional context**
Introduced in PR #597

**Comment by maimoona-bashir** [comment]
This has been fixed.
