### ISSUE TITLE
New background image for opening screen

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/Program-Wars#601]
**Is your feature request related to a problem? Please describe.**
When the PW open screen was created by @vincentcote87, we were thinking about how we'll use different programming languages for the user study and/or how PW was not tied to a specific programming language. After years of looking at it, I'm tired of it and I think it is too "busy".

**Describe the solution you'd like**
Something cleaner. Maybe a greyed-out version of the PW logo (if we ever get #19 resolved! 😉 )

**Comment by jsanvik** [comment]
Until we have a logo, I like the idea of a simple gradient as a background. Simple but not boring

**Comment by strinsberg** [comment]
I think a gradient could work nicely, and we could even do it with CSS which would mean that we wouldn't need an image.

**Comment by strinsberg** [comment]
Here is what I have set the home page background to for testing in Version3. It should give an idea for what it could look like with just CSS setting a gradient. If this is the kind of thing we are talking about then we could easily add it in the direction and with the colors that people feel are most appropriate to version2.

![Screenshot from 2020-07-14 17-55-46](https://user-images.githubusercontent.com/45857986/87487705-9c6be000-c5fb-11ea-8d21-0cc40901b1c9.png)

**Comment by jsanvik** [comment]
Gradient looks nice

**Comment by strinsberg** [comment]
I have been using this kind of thing with version 3 for all setup screens now. I will probably submit a quick pull request to change it for version 2, and then we can close this. I don't think @jsanvik should worry about coming up with a new image anymore, unless anyone doesn't like the gradient. I think one of the main benefits is that it allows us to add some colour to the screens without adding any content that might distract from the task at hand.

**Comment by jsanvik** [comment]
Gradient looks good.

**Comment by strinsberg** [comment]
The new gradient is merged, so I am going to close this.
