### ISSUE TITLE
Update DeepScan to work with PW

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/Program-Wars#622]
**Describe the bug**
DeepScan stopped working for the project.
**Expected behavior**
DeepScan runs on each pull request.

**Screenshots**

![image](https://user-images.githubusercontent.com/28762049/88695494-3c773e00-d0bf-11ea-9514-e992a21c661a.png)

**Additional context**
Likely due to the move from the "johnanvik" namespace to "SibylLab" in May.

**Comment by johnanvik** [comment]
@strinsberg, I have DeepScan working. It spotted these three issues. Please look at them and let me know if they need addressing.

https://deepscan.io/dashboard#view=project&tid=10352&pid=13104&bid=214253

**Comment by strinsberg** [comment]
They are small things that should not affect the running of the game, but I will correct them sometime soon as they are very simple.
