### ISSUE TITLE
Editor Window Interface Metaphor

### ISSUE THREAD

**Issue by vincentcote87** [SibylLab/Program-Wars#98]
Changing the play area to look more like a terminal window, when the player adds cards down to the terminal window it adds it in as "code".

**Comment by johnanvik** [comment]
@groadybones We may want to look at this as goal this summer.

**Comment by groadybones** [comment]
I can implement this when as I work on #482 because I'm going to have to completely rework the playfields anyway

**Comment by johnanvik** [comment]
@hastar07, you may want to consider this graphical change.

**Comment by johnanvik** [comment]
This seems related to changing the interface for #538
